name: Lint

on:
  push:
    branches:
      - nifty-ink-dev
  pull_request:
    branches:
      - nifty-ink-dev

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run nextjs lint
        run: yarn next:lint

      - name: Check typings on nextjs
        run: yarn next:check-types

      - name: Check typings on nifty-view
        run: yarn nifty-view:check-types
